global:
  tcp:
    listenaddr: :50050
  http:
    listenaddr: :8081
    listenaddrtls: :8555
rtsp:
  loglevel: trace
  tcp:
    listenaddr:
  push:
    pushlist:
      live/test: rtsp://localhost/live/test
flv:
  publish:
    pubaudio: false
  pull:
    pullonstart:
      live/test: /Users/dexter/Movies/jb-demo.flv