global:
  # loglevel: debug
  tcp:
    listenaddr: :50051
console:
  secret: de2c0bb9fd47684adc07a426e139239b
webrtc:
  publish:
    pubaudio: false
rtmp:
  chunksize: 2048
  subscribe:
    # submode: 1
    subaudio: false
