global:
  loglevel: debug
  tcp:
    listenaddr: :50051
console:
  secret: 00aea3af031f134d6307618b05ec4899
rtmp:
  enable: false
rtsp:
  enable: false
webrtc:
  enable: false
hdl:
  pull:
    pullonstart:
      live/test: /Users/dexter/Movies/jb-demo.flv