global:
  loglevel: debug
srt:
  listenaddr: :6000
  passphrase: foobarfoobar
gb28181:
  autoinvite: true
  sip:
    listenaddr:
          - udp::5060
  onsub:
    pull:
      .* : $0
mp4:
  publish:
    delayclosetimeout: 3s
  onsub:
    pull:
      ^vod/(.+)$: $1
hls:
  onpub:
    transform:
      .* : 5s x 3
