global:
  location:
    "^/hdl/(.*)": "/flv/$1"
  loglevel: debug
  enablelogin: false
  # db:
  #   dbtype: mysql
  #   dsn: root:Monibuca#!4@tcp(sh-cynosdbmysql-grp-kxt43lv6.sql.tencentcdb.com:28520)/lkm7s_v5?parseTime=true
srt:
  listenaddr: :6000
  passphrase: foobarfoobar
gb28181:
  enable: false
  autoinvite: true
  sip:
    listenaddr:
          - udp::5060
  # pull:
  #   live/test: dump/34020000001320000001
  onsub:
    pull:
      .* : $0
mp4:
  # enable: false
  # publish:
  #   delayclosetimeout: 3s

  onsub:
    pull:
      ^vod_mp4_\d+/(.+)$: $1
cascadeserver:
  quic:
    listenaddr: :44944
# llhls:
#   onpub:
#     transform:
#       .* : 1s x 7
flv:
  # onpub:
  #   record:
  #     ^live/.+:
  #         fragment: 1m
  #         filepath: record/$0
  onsub:
    pull:
      ^vod_flv_\d+/(.+)$: $1
#   pull:
#     live/test: https://livecb.alicdn.com/mediaplatform/afb241b3-408c-42dd-b665-04d22b64f9df.flv?auth_key=1734575216-0-0-c62721303ce751c8e5b2c95a2ec242a0&F=pc&source=34675810_null_live_detail&ali_flv_retain=2
hls:
  # pull:
  #   live/test: https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/gear3/prog_index.m3u8
#   onpub:
#     transform:
#       .* : 5s x 3
#rtsp:
#  pull:
    # live/test: rtsp://admin:1qaz2wsx3EDC@giroro.tpddns.cn:1554/Streaming/Channels/101
#    live/test: rtsp://admin:1qaz2wsx3EDC@localhost:8554/live/test

snap:
  enable: false
  ismanualmodesave: true  # 手动截图是否保存文件
  watermark:
    text: "Monibuca $T{2006-01-02 15:04:05.000}"
    fontpath: "/System/Library/Fonts/STHeiti Light.ttc" # mac字体路径
    # fontpath: "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc" # linux字体路径 思源黑体
    # fontpath: "C:/Windows/Fonts/msyh.ttf" # windows字体路径 微软雅黑
    fontsize: 16
    fontspacing: 2  # 添加字体间距配置
    fontcolor: "rgba(255,165,0,1)"
    offsetx: 10
    offsety: 10  
  mode: 2 #截图模式：0-时间间隔，1-关键帧间隔 2-HTTP请求模式（手动触发）
  timeinterval: 3s
  savepath: "./snap"
  iframeinterval: 3 # 截图i帧间隔，默认为3，即每隔3个i帧截图一次
  querytimedelta: 3  # 查询截图时允许的最大时间差（秒）
  filter: "^live/.*"
  onpub:
    transform:
      .* : $0

crypto:
  enable: false
  isstatic: false
  algo: aes_ctr # 加密算法 支持 aes_ctr xor_c
  encryptlen: 1024
  secret:
    key: your key
    iv: your iv
  onpub:
    transform:
      .* : $0