global:
  loglevel: debug
srt:
  listenaddr: :6000
  passphrase: foobarfoobar
gb28181:
  autoinvite: true
  sip:
    listenaddr:
          - udp::5060
  onsub:
    pull:
      .* : $0
mp4:
  onsub:
    pull:
      ^vod/(.+)$: live/$1
