global:
#  loglevel: debug
  enableauth: true
  tcp:
    listenaddr: :50051
#    ringsize: 20-250
#    buffertime: 10s
  #   speed: 1
console:
  secret: de2c0bb9fd47684adc07a426e139239b
logrotate:
  level: debug
rtsp:
rtmp:
#  tcp:
#    listenaddr: :11935
  publish:
    # idletimeout: 10s
    # closedelaytimeout: 4s
  subscribe:
    # submode: 1
    # subaudio: false
  pull:
    pullonsub:
      live/pull: rtmp://localhost/live/test
# hdl:
#   pull:
#     pullonstart:
#       live/test: /Users/dexter/Movies/jb-demo.flv