global:
  loglevel: trace
  tcp:
    listenaddr: :50052
  http:
    listenaddr: :8081
    listenaddrtls: :8555
rtmp:
  tcp:
    listenaddr: :1936
hdl:
  publish:
    # speed: 2
  pull:
    pullonstart:
      live/test: http://localhost:8080/hdl/live/test.flv