global:
  loglevel: info
  tcp:
    listenaddr: :50051
  http:
    listenaddr: :8081
    listenaddrtls: :8555
rtmp:
  tcp:
    listenaddr: 
  push:
    pushlist:
      live/test: rtmp://localhost/live/test
flv:
  pull:
    pullonstart:
      live/test: /Users/dexter/Movies/jb-demo.flv